# Generated by Django 5.2.16 on 2026-08-06 18:43

import agenda.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cursos", "0007_alter_comision_options_alter_entregaalumno_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventoCalendario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("clase", "Clase"),
                            ("parcial", "Parcial"),
                            ("final", "Final"),
                            ("entrega", "Entrega"),
                            ("personal", "Personal"),
                        ],
                        default="personal",
                        max_length=20,
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        help_text="Fecha del evento; si se repite, la de la primera ocurrencia."
                    ),
                ),
                ("todo_el_dia", models.BooleanField(default=False)),
                ("hora_inicio", models.TimeField(blank=True, null=True)),
                ("hora_fin", models.TimeField(blank=True, null=True)),
                ("lugar", models.CharField(blank=True, max_length=120)),
                (
                    "repeticion",
                    models.CharField(
                        choices=[
                            ("ninguna", "No se repite"),
                            ("semanal", "Todas las semanas"),
                        ],
                        default="ninguna",
                        max_length=20,
                    ),
                ),
                (
                    "repetir_hasta",
                    models.DateField(
                        blank=True,
                        help_text="Última fecha en la que se repite (inclusive).",
                        null=True,
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_calendario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_calendario",
                        to="cursos.materia",
                    ),
                ),
            ],
            options={
                "db_table": "evento_calendario",
                "ordering": ["fecha", "hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Apunte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("apunte", "Apunte"),
                            ("grabacion", "Grabación"),
                            ("enlace", "Enlace"),
                        ],
                        default="apunte",
                        max_length=20,
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        upload_to=agenda.models.ruta_archivo_apunte,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "odt",
                                    "ppt",
                                    "pptx",
                                    "xls",
                                    "xlsx",
                                    "csv",
                                    "txt",
                                    "md",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "heic",
                                    "zip",
                                    "mp3",
                                    "m4a",
                                    "wav",
                                    "ogg",
                                    "opus",
                                    "mp4",
                                    "webm",
                                    "mov",
                                ]
                            )
                        ],
                    ),
                ),
                ("nombre_archivo", models.CharField(blank=True, max_length=255)),
                ("tamano_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "enlace",
                    models.URLField(
                        blank=True,
                        help_text="Alternativa al archivo: Drive, YouTube, etc.",
                    ),
                ),
                (
                    "visibilidad",
                    models.CharField(
                        choices=[
                            ("privado", "Privado"),
                            ("comision", "Compartido con la comisión"),
                        ],
                        default="privado",
                        max_length=20,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apuntes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apuntes",
                        to="cursos.materia",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        blank=True,
                        help_text="Clase o examen del calendario al que pertenece el apunte.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="apuntes",
                        to="agenda.eventocalendario",
                    ),
                ),
            ],
            options={
                "db_table": "apunte",
                "ordering": ["-creado_en", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="eventocalendario",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("hora_fin__isnull", True),
                        ("hora_inicio__isnull", True),
                        ("todo_el_dia", True),
                    ),
                    models.Q(
                        ("hora_fin__isnull", False),
                        ("hora_inicio__isnull", False),
                        ("todo_el_dia", False),
                    ),
                    _connector="OR",
                ),
                name="evento_calendario_horario_segun_todo_el_dia",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventocalendario",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("hora_inicio__isnull", True),
                    ("hora_fin__gt", models.F("hora_inicio")),
                    _connector="OR",
                ),
                name="evento_calendario_hora_fin_gt_inicio",
            ),
        ),
        migrations.AddConstraint(
            model_name="eventocalendario",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("repeticion", "ninguna"), ("repetir_hasta__isnull", True)
                    ),
                    models.Q(
                        ("repeticion", "semanal"), ("repetir_hasta__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="evento_calendario_repetir_hasta_si_repite",
            ),
        ),
        migrations.AddConstraint(
            model_name="apunte",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("archivo", ""), _negated=True),
                    models.Q(("enlace", ""), _negated=True),
                    _connector="OR",
                ),
                name="apunte_archivo_o_enlace",
            ),
        ),
        migrations.AddConstraint(
            model_name="apunte",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("visibilidad", "privado"),
                    ("materia__isnull", False),
                    _connector="OR",
                ),
                name="apunte_compartido_requiere_materia",
            ),
        ),
    ]
