# Generated by Django 5.2.16 on 2026-07-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carrera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "carrera",
            },
        ),
        migrations.CreateModel(
            name="Comision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo", models.CharField(help_text="ej. 2026-2S", max_length=20)),
                ("cupo", models.PositiveSmallIntegerField()),
                ("aula", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "db_table": "comision",
            },
        ),
        migrations.CreateModel(
            name="Entrega",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_limite", models.DateField()),
                (
                    "puntaje_maximo",
                    models.DecimalField(decimal_places=2, default=100, max_digits=5),
                ),
            ],
            options={
                "db_table": "entrega",
            },
        ),
        migrations.CreateModel(
            name="EntregaAlumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_envio", models.DateTimeField(blank=True, null=True)),
                ("archivo_url", models.TextField(blank=True)),
                (
                    "nota",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("entregado", "Entregado"),
                            ("corregido", "Corregido"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "entrega_alumno",
            },
        ),
        migrations.CreateModel(
            name="InscripcionComision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inscripcion", models.DateField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activa", "Activa"),
                            ("abandonada", "Abandonada"),
                            ("aprobada", "Aprobada"),
                            ("desaprobada", "Desaprobada"),
                        ],
                        default="activa",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "inscripcion_comision",
            },
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("creditos", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "materia",
            },
        ),
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "modulo",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="Recurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("archivo", "Archivo"),
                            ("video", "Video"),
                            ("link", "Link"),
                            ("texto", "Texto"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("url_o_contenido", models.TextField()),
                ("orden", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "recurso",
                "ordering": ["orden"],
            },
        ),
    ]
