# Generated by Django 5.2.16 on 2026-07-23 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cursos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comision",
            name="docente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comisiones_a_cargo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="entregaalumno",
            name="alumno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entregas_realizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="entregaalumno",
            name="entrega",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entregas_alumnos",
                to="cursos.entrega",
            ),
        ),
        migrations.AddField(
            model_name="inscripcioncomision",
            name="alumno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inscripciones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="inscripcioncomision",
            name="comision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inscripciones",
                to="cursos.comision",
            ),
        ),
        migrations.AddField(
            model_name="materia",
            name="carrera",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="materias",
                to="cursos.carrera",
            ),
        ),
        migrations.AddField(
            model_name="comision",
            name="materia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comisiones",
                to="cursos.materia",
            ),
        ),
        migrations.AddField(
            model_name="modulo",
            name="comision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modulos",
                to="cursos.comision",
            ),
        ),
        migrations.AddField(
            model_name="entrega",
            name="modulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entregas",
                to="cursos.modulo",
            ),
        ),
        migrations.AddField(
            model_name="recurso",
            name="modulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recursos",
                to="cursos.modulo",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="entregaalumno",
            unique_together={("entrega", "alumno")},
        ),
        migrations.AlterUniqueTogether(
            name="inscripcioncomision",
            unique_together={("alumno", "comision")},
        ),
    ]
