# Generated by Django 5.2.16 on 2026-07-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inscripcioncomision",
            options={"ordering": ["-fecha_inscripcion"]},
        ),
    ]
