# Generated by Django 5.2.16 on 2026-07-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0003_alter_inscripcioncomision_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entrega",
            options={"ordering": ["fecha_limite"]},
        ),
    ]
