# Generated by Django 5.2.16 on 2026-07-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0004_alter_entrega_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materia",
            options={"ordering": ["semestre", "codigo"]},
        ),
        migrations.AddField(
            model_name="materia",
            name="semestre",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Semestre de la malla curricular (1-10), si aplica.",
                null=True,
            ),
        ),
    ]
