# Generated by Django 5.2.16 on 2026-07-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0006_seed_malla_iis"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comision",
            options={"ordering": ["-periodo", "materia__codigo"]},
        ),
        migrations.AlterModelOptions(
            name="entregaalumno",
            options={"ordering": ["-id"]},
        ),
    ]
