# Generated by Django 5.2.16 on 2026-07-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autoevaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "puntaje",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("total_preguntas", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "db_table": "autoevaluacion",
            },
        ),
        migrations.CreateModel(
            name="BloqueEstudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("estudio", "Estudio"),
                            ("repaso", "Repaso"),
                            ("entrega", "Entrega"),
                            ("examen", "Examen"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha", models.DateField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("planificado", "Planificado"),
                            ("cumplido", "Cumplido"),
                            ("salteado", "Salteado"),
                        ],
                        default="planificado",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "bloque_estudio",
                "ordering": ["fecha", "hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Habito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "frecuencia",
                    models.CharField(
                        choices=[
                            ("diaria", "Diaria"),
                            ("semanal", "Semanal"),
                            ("dias_especificos", "Días específicos"),
                        ],
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "habito",
            },
        ),
        migrations.CreateModel(
            name="ItemRepaso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta", models.TextField()),
                ("respuesta", models.TextField()),
                (
                    "facilidad",
                    models.DecimalField(decimal_places=2, default=2.5, max_digits=4),
                ),
                ("intervalo_dias", models.PositiveIntegerField(default=0)),
                ("repeticiones", models.PositiveIntegerField(default=0)),
                ("proxima_fecha_repaso", models.DateField()),
            ],
            options={
                "db_table": "item_repaso",
            },
        ),
        migrations.CreateModel(
            name="PreguntaAutoevaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enunciado", models.TextField()),
                ("respuesta_correcta", models.TextField()),
                ("respuesta_alumno", models.TextField(blank=True)),
                ("es_correcta", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "pregunta_autoevaluacion",
            },
        ),
        migrations.CreateModel(
            name="Recordatorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrega_proxima", "Entrega próxima"),
                            ("examen_proximo", "Examen próximo"),
                            ("habito", "Hábito"),
                            ("repaso_espaciado", "Repaso espaciado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("fecha_hora_envio", models.DateTimeField()),
                (
                    "canal",
                    models.CharField(
                        choices=[("push", "Push"), ("email", "Email")],
                        default="push",
                        max_length=20,
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("enviado", "Enviado"),
                            ("leido", "Leído"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "recordatorio",
            },
        ),
        migrations.CreateModel(
            name="RegistroHabito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("cumplido", models.BooleanField()),
            ],
            options={
                "db_table": "registro_habito",
            },
        ),
        migrations.CreateModel(
            name="SesionRepaso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "calificacion",
                    models.CharField(
                        choices=[
                            ("otra_vez", "Otra vez"),
                            ("dificil", "Difícil"),
                            ("bien", "Bien"),
                            ("facil", "Fácil"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "sesion_repaso",
            },
        ),
    ]
