# Generated by Django 5.2.16 on 2026-07-23 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cursos", "0002_initial"),
        ("productividad", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="autoevaluacion",
            name="alumno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="autoevaluaciones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="autoevaluacion",
            name="materia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="autoevaluaciones",
                to="cursos.materia",
            ),
        ),
        migrations.AddField(
            model_name="bloqueestudio",
            name="alumno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bloques_estudio",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bloqueestudio",
            name="materia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bloques_estudio",
                to="cursos.materia",
            ),
        ),
        migrations.AddField(
            model_name="habito",
            name="alumno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habitos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemrepaso",
            name="alumno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items_repaso",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="itemrepaso",
            name="materia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_repaso",
                to="cursos.materia",
            ),
        ),
        migrations.AddField(
            model_name="itemrepaso",
            name="recurso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items_repaso",
                to="cursos.recurso",
            ),
        ),
        migrations.AddField(
            model_name="preguntaautoevaluacion",
            name="autoevaluacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preguntas",
                to="productividad.autoevaluacion",
            ),
        ),
        migrations.AddField(
            model_name="recordatorio",
            name="alumno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordatorios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="recordatorio",
            name="entrega",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordatorios",
                to="cursos.entrega",
            ),
        ),
        migrations.AddField(
            model_name="recordatorio",
            name="habito",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordatorios",
                to="productividad.habito",
            ),
        ),
        migrations.AddField(
            model_name="recordatorio",
            name="item_repaso",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recordatorios",
                to="productividad.itemrepaso",
            ),
        ),
        migrations.AddField(
            model_name="registrohabito",
            name="habito",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registros",
                to="productividad.habito",
            ),
        ),
        migrations.AddField(
            model_name="sesionrepaso",
            name="item_repaso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sesiones",
                to="productividad.itemrepaso",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="registrohabito",
            unique_together={("habito", "fecha")},
        ),
    ]
