# Generated by Django 5.2.16 on 2026-07-23 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0002_initial"),
        ("productividad", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bloqueestudio",
            constraint=models.CheckConstraint(
                condition=models.Q(("hora_fin__gt", models.F("hora_inicio"))),
                name="bloque_estudio_hora_fin_gt_inicio",
            ),
        ),
    ]
