# Generated by Django 5.2.16 on 2026-07-23 17:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productividad", "0003_bloqueestudio_bloque_estudio_hora_fin_gt_inicio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemrepaso",
            name="proxima_fecha_repaso",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
