# Generated by Django 5.2.16 on 2026-07-23 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productividad", "0005_tareas_periodicas_recordatorios"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autoevaluacion",
            options={"ordering": ["-fecha", "-id"]},
        ),
        migrations.AlterModelOptions(
            name="habito",
            options={"ordering": ["nombre"]},
        ),
        migrations.AlterModelOptions(
            name="itemrepaso",
            options={"ordering": ["proxima_fecha_repaso"]},
        ),
        migrations.AlterModelOptions(
            name="preguntaautoevaluacion",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="recordatorio",
            options={"ordering": ["-fecha_hora_envio"]},
        ),
        migrations.AlterModelOptions(
            name="registrohabito",
            options={"ordering": ["-fecha"]},
        ),
        migrations.AlterModelOptions(
            name="sesionrepaso",
            options={"ordering": ["-fecha", "-id"]},
        ),
    ]
