# Generated by Django 5.2.16 on 2026-07-23 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cursos", "0007_alter_comision_options_alter_entregaalumno_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MesaExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("final", "Final"),
                            ("recuperatorio", "Recuperatorio"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "docente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mesas_presididas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mesas_examen",
                        to="cursos.materia",
                    ),
                ),
            ],
            options={
                "db_table": "mesa_examen",
                "ordering": ["fecha"],
            },
        ),
        migrations.CreateModel(
            name="SolicitudTramite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            (
                                "certificado_alumno_regular",
                                "Certificado de alumno regular",
                            ),
                            ("certificado_analitico", "Certificado analítico"),
                            (
                                "constancia_titulo_en_tramite",
                                "Constancia de título en trámite",
                            ),
                        ],
                        max_length=40,
                    ),
                ),
                ("fecha_solicitud", models.DateField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("emitido", "Emitido"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_tramite",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "solicitud_tramite",
                "ordering": ["-fecha_solicitud", "-id"],
            },
        ),
        migrations.CreateModel(
            name="InscripcionMesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inscripcion", models.DateField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("inscripto", "Inscripto"),
                            ("ausente", "Ausente"),
                            ("aprobado", "Aprobado"),
                            ("desaprobado", "Desaprobado"),
                        ],
                        default="inscripto",
                        max_length=20,
                    ),
                ),
                (
                    "nota",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscripciones_mesa",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mesa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inscriptos",
                        to="tramites.mesaexamen",
                    ),
                ),
            ],
            options={
                "db_table": "inscripcion_mesa",
                "ordering": ["-fecha_inscripcion"],
                "unique_together": {("alumno", "mesa")},
            },
        ),
    ]
